FROM docker.io/golang:alpine AS compile-image
WORKDIR /src
ADD src/apiserver.go __version__ ./
RUN go mod init apiserver && go mod tidy && go build -ldflags="-X 'main.Version=$(cat __version__)'"

FROM docker.io/alpine
COPY --from=compile-image /src/apiserver /apiserver
ENTRYPOINT ["/apiserver"]
