# Список этапов
stages:
  - compile
  - build
  - deploy
  - clean

# Используемые переменные
variables:
  # Переменная, указывающая какой Dockerfile использовать для сборки образа
  #DFILE: "full"
  DFILE: "art"
  # Переменная названия окружения, значение по умолчанию
  CLUSTER_ENV: "stage"
  # Константа получения описания сборки - либо тэг, либо тэг, дополненный сборкой
  VERSION_CMD: "git describe --always --tags"

# Шаг компиляции приложения
Compile:
  # Этап, к которому относится данный шаг
  stage: compile
  #only:
  #  changes:
  #    - "**/*.go"
  # Переменные шага
  variables:
    #DFILE: "art"
    # Указание использовать чистый репозиторий (склонировать заново), вместо кэша (fetch)
    GIT_STRATEGY: clone
  # Тэги по которым выбирается Runner
  tags:
    - linux
    - podman
  # Команды выполняемые Runner
  script:
    - $VERSION_CMD > __version__
    - echo "Compiling application v$(cat __version__)..."
    - podman run --rm -v ./src:/src docker.io/golang:alpine sh -c "cd /src && go mod init apiserver && go mod tidy && go build -ldflags=\"-X 'main.Version=$(cat __version__)'\""
  # Указание на сохранение артефактов - исполяемого файла приложения
  artifacts:
    paths:
      - src/apiserver

# Шаг сборки образа с приложением - этап build
Build image:
  stage: build
  # Условия запуска шага - при условии успешного выполнения предыдущего
  when: on_success
  # Что требуется для запуска шага - по умолчанию, завершение предыдущего шага
  # Данным блоком можно изменить последовательность выполнения шагов
  needs:
    - Compile
  # Указания, артефакты каких шагов нужно выгружать.
  # По умолчанию, выгружаются все предыдущие.
  dependencies:
    - Compile
  tags:
    - podman
  script:
    - echo "Building image with strategy $DFILE..."
    - $VERSION_CMD > __version__
    - bash build.sh --build-$DFILE

# Шаг выгрузки образа во внешний Registry этапа build
Push image:
  stage: build
  # Условие запуска шага - требуется ручной запуск
  when: manual
  needs:
    - Build image
  tags: ['podman']
  script:
    - echo "Pushing image to registry..."
    - $VERSION_CMD > __version__
    - podman login docker.io -u $(echo $GH_USER | base64 -d) -p $(echo $GH_PASSWORD | base64 -d)
    - bash build.sh --push
    - podman logout --all

# Шаг разворачивания приложения в кластере Kubernetes этапа deploy в окружении stage
Deploy STAGE:
  stage: deploy
  when: on_success
  needs:
    - Push image
  tags: ['podman']
  script:
    - export APP_IMAGE_TAG=$($VERSION_CMD)
    - echo "Deploying application v$APP_IMAGE_TAG for $CLUSTER_ENV..."
    - bash build.sh --deploy

# Шаг разворачивания приложения в кластере Kubernetes этапа deploy в окружении prod
Deploy PROD:
  stage: deploy
  when: manual
  needs:
    - Push image
  # Условия необходимости выполнения шага
  rules:
    # Если существует переменная CI_COMMIT_TAG (доступна только в типе события Tag Commiting) и она удовлетворяет шаблону регулярного выражения
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+|)$/
      # Для шага меняются значения переменных
      variables:
        CLUSTER_ENV: "prod"
        APP_IMAGE_TAG: $CI_COMMIT_TAG
  tags: ['podman']
  script:
    - echo "Deploying application v$APP_IMAGE_TAG for $CLUSTER_ENV..."
    - bash build.sh --deploy

# Шаг удаления приложения из кластера Kubernetes для окружения stage
Clean STAGE:
  stage: clean
  when: manual
  needs:
    - Deploy STAGE
  tags: ['podman']
  script:
    - export APP_IMAGE_TAG=$($VERSION_CMD)
    - echo "Destroy application v$APP_IMAGE_TAG at $CLUSTER_ENV..."
    - bash build.sh --clean

# Шаг удаления приложения из кластера Kubernetes для окружения prod
Clean PROD:
  stage: clean
  when: manual
  needs:
    - Deploy PROD
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+|)$/
      variables:
        CLUSTER_ENV: "prod"
        APP_IMAGE_TAG: $CI_COMMIT_TAG
  tags: ['podman']
  script:
    - echo "Destroy application v$APP_IMAGE_TAG at $CLUSTER_ENV..."
    - bash build.sh --clean
