---
# IP адрес SSH бастиона. Определяется переменной окружения, которая в свою очередь устанавливается скриптом go.sh через утилиту управления Яндекс.Облаком
bastion_host: "{{ lookup('ansible.builtin.env', 'BASTION_IP') }}"
# Используемый порт для подключения к бастиону по SSD - используется стандартны
bastion_port: 22
# Пользователь для подключения к SSH бастиону. Определяется переменной окружения, которая в свою очередь устанавливается скриптом go.sh через утилиту управления Яндекс.Облаком
bastion_user: "{{ lookup('ansible.builtin.env', 'BASTION_USER') }}"

# Порт бастиона, выделенный для GitLab
bastion_gitlab: 8000
# Порт бастиона, выделенный для доступа к Git внутри GitLab
bastion_git: 8001
# Порт бастиона, выделенный для доступа к InfluxDB
bastion_influxdb: 8010
# Порт бастиона, выделенный для доступа к Grafana (статистика основных хостов)
bastion_grafana: 8011
# Порт бастиона, выделенный для доступа к Grafana (статистика кластера kubernetes)
bastion_grafana_kube: 8012
# Порт бастиона, выделенный для отображения статистики HAProxy узла бастиона
bastion_haproxy_main: 8020
# Порт бастиона, выделенный для отображения статистики HAProxy узла proxy кластера kubernetes
bastion_haproxy_kube: 8021
# Порты бастиона, выделенные для доступа к приложения в соответствующем окружении
bastion_app:
  stage: 8030
  prod: 8033

# Файл ключа для доступа по SSH к бастиону
bastion_key: "../secrets/key_bastion"
# Файл ключа для доступа по SSH к основным машинкам
machine_key: "../secrets/key_machine"
# Файл ключа для доступа по SSH к машинках kubernetes кластера
kube_key: "../secrets/key_kube"
# Имя пользователя для доступа к статистике HAProxy (обоих узлов)
haproxy_stats_user: "root"
# Пароль для доступа к статистике HAProxy (обоих узлов)
haproxy_stats_password: "haproxy"
...
