---
# Используемая версия kubernetes
kube_version: "1.28.2"

# Внутренний порт api сервера
kube_api_port: "6443"
# Используемые кластером сетевые адреса 
kube_network_cidr: "192.168.100.0/24"

# Список манифестов применяемых при разворачивании кластера
kube_manifests:
  - "https://docs.projectcalico.org/manifests/calico.yaml"
  #- "https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml"
  # - "https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml"

# Используемая версия qbec - при комментировании устанавливаться не будет
qbec_version: "0.15.2"
# Используемая версия helm - при комментировании устанавливатсья не будет
#helm_version: "3.12.3"
# Используемая версия containerd

containerd_version: "1.7.6"
# Интернет адрес архива containerd
containerd_link: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
# Интернет адрес service файла containerd
containerd_service_link: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
# Образ используемый containerd в качестве sandbox
containerd_sandbox_image: "registry.k8s.io/pause:3.9"
# Используемая версия runc
runc_version: "1.1.9"
# Интернет адрес архива runc
runc_link: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
# Используемая версия CNI плагинов
cni_plugins_version: "1.3.0"
# Интернет адрес архива CNI плагинов
cni_plugins_link: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz"
...
