---
# Общие параметры
runner_home: "/home/{{ ansible_user }}/gitlab-runner"
runner_token: "glrt-NZYEfymt7sqf-FGjfS2N"
# Используется при регистрации SHELL
runner_name: "ShellRunner"
# Используется при регистрации DOCKER
runner_version: "alpine-v16.3.0"
runner_port: 8093
runner_image: "golang:1.21.1-alpine"
...
