---
all:
  hosts:
    bastion:
      ansible_host: "{{ bastion_host }}"
      ansible_port: "{{ bastion_port }}"
      ansible_user: "{{ bastion_user }}"
      ansible_ssh_private_key_file: "{{ bastion_key }}"
      ansible_ssh_common_args: ""
    vm-main-1:
      ansible_host: "192.168.1.11"
      ansible_port: 22
      ansible_user: "debian"
    vm-main-2:
      ansible_host: "192.168.1.12"
      ansible_port: 22
      ansible_user: "debian"
    vm-main-3:
      ansible_host: "192.168.1.13"
      ansible_port: 22
      ansible_user: "debian"
  vars:
    ansible_ssh_private_key_file: "{{ machine_key }}"
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -p {{ bastion_port }} -W %h:%p -q
      -i {{ bastion_key }} {{ bastion_user }}@{{ bastion_host }}"
  children:
    gitlab:
      hosts:
        vm-main-1:
    runner:
      hosts:
        vm-main-3:
    grafana:
      hosts:
        vm-main-2:
    influxdb:
      hosts:
        vm-main-2:
    telegraf:
      hosts:
        vm-main-1:
        vm-main-2:
        vm-main-3:
    kube_proxy:
      hosts:
        vm-main-3:
      vars:
        kube_api_proxy_port:
          stage: "8603"
          prod: "8604"
    kube_master:
      hosts:
      vars:
        ansible_ssh_private_key_file: "{{ kube_key }}"
        app_port:
          stage: "30600"
          prod: "30700"
    kube_worker:
      hosts:
      vars:
        ansible_ssh_private_key_file: "{{ kube_key }}"
...
