---
all:
  hosts:
    bastion:
      ansible_host: "{{ bastion_host }}"
      ansible_port: "{{ bastion_port }}"
      ansible_user: "{{ bastion_user }}"
      ansible_ssh_private_key_file: "{{ bastion_key }}"
      ansible_ssh_common_args: ""
    vm-main-1:
      ansible_host: "192.168.1.11"
      ansible_port: 22
      ansible_user: "debian"
    vm-main-2:
      ansible_host: "192.168.1.12"
      ansible_port: 22
      ansible_user: "debian"
    vm-main-3:
      ansible_host: "192.168.1.13"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-1:
      ansible_host: "192.168.10.51"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-2:
      ansible_host: "192.168.20.51"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-3:
      ansible_host: "192.168.30.51"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-4:
      ansible_host: "192.168.10.101"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-5:
      ansible_host: "192.168.20.101"
      ansible_port: 22
      ansible_user: "debian"
    vm-kube-6:
      ansible_host: "192.168.30.101"
      ansible_port: 22
      ansible_user: "debian"
  vars:
    ansible_ssh_private_key_file: "{{ machine_key }}"
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -p {{ bastion_port }} -W %h:%p -q
      -i {{ bastion_key }} {{ bastion_user }}@{{ bastion_host }}"
  children:
    gitlab:
      hosts:
        vm-main-1:
    runner:
      hosts:
        vm-main-3:
    grafana:
      hosts:
        vm-main-2:
    influxdb:
      hosts:
        vm-main-2:
    telegraf:
      hosts:
        vm-main-1:
        vm-main-2:
        vm-main-3:
    kube_proxy:
      hosts:
        vm-main-3:
    kube_master:
      hosts:
        vm-kube-1:
        vm-kube-2:
        vm-kube-3:
      vars:
        ansible_ssh_private_key_file: "{{ kube_key }}"
    kube_worker:
      hosts:
        vm-kube-4:
        vm-kube-5:
        vm-kube-6:
      vars:
        ansible_ssh_private_key_file: "{{ kube_key }}"
...
