---
- name: Configure routes on Bastion host
  hosts: bastion
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
      - haproxy
      - curl
      - htop
    - name: Generate HAProxy configuration file
      ansible.builtin.template:
        src: "haproxy_bastion.cfg.jinja2"
        dest: "/etc/haproxy/haproxy.cfg"
      notify:
      - Restart HAProxy
  handlers:
    - name: Restart HAProxy
      ansible.builtin.service:
        name: "haproxy"
        state: restarted
...
