---
- name: Add kubernetes hosts
  ansible.builtin.import_playbook: dynamic_inv.yml

- name: Check cluster presence
  hosts: kube_nodes
  tasks:
    - name: Get kubelet status
      ansible.builtin.command: "systemctl is-active kubelet"
      register: kbl_res
      changed_when: false
      ignore_errors: true
    - name: Exit if there is no active kubelet
      meta: end_host
      when: kbl_res.stdout != "active"
    - name: Reset cluster node by kubeadm
      become: true
      ansible.builtin.command: "kubeadm reset -f"
    - name: Remove CNI configuration
      become: true
      ansible.builtin.file:
        path: "/etc/cni/net.d"
        state: absent
    - name: Remove kubeconfig
      ansible.builtin.file:
        path: "~/.kube/config"
        state: absent

- name: Create main control plane
  hosts: kube_master[0]
  become: true
  tasks:
    - name: Initialize main control plane
      ansible.builtin.command: "kubeadm init --pod-network-cidr {{ kube_network_cidr }} --control-plane-endpoint {{ hostvars[groups.kube_proxy.0].ansible_host }}:{{ kube_api_proxy_port }}"
      register: adm_res
    - name: Get admin config file
      ansible.builtin.fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "files/_kube_admin.conf"
        flat: true
    - name: Generate certificate keys
      ansible.builtin.shell: "kubeadm init phase upload-certs --upload-certs | tail -n1"
      register: cert_key
    - name: Generate token for joining
      ansible.builtin.command: "kubeadm token create --print-join-command"
      register: kube_join
    - name: Create join command to control planes
      become: false
      ansible.builtin.copy:
        content: "{{ kube_join.stdout_lines[0] }} --control-plane --certificate-key {{ cert_key.stdout_lines[0] }}"
        dest: "files/_kube_join_controlplane"
        mode: 0777
      delegate_to: localhost
    - name: Create join command to workers
      become: false
      ansible.builtin.copy:
        content: "{{ kube_join.stdout_lines[0] }}"
        dest: "files/_kube_join_worker"
        mode: 0777
      delegate_to: localhost

- name: Copy admin kube config at kube proxy
  hosts: kube_proxy
  vars:
    tf_workspace: "{{ lookup('ansible.builtin.env', 'TF_WORKSPACE', default='default') }}"
    kube_config: "/home/{{ ansible_user }}/.kube/config_{{ tf_workspace }}"
  tasks:
    - name: Create directory for kube config
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: 0755
    - name: Copy admin config to user`s home
      ansible.builtin.copy:
        src: "files/_kube_admin.conf"
        dest: "{{ kube_config }}"
        mode: 0644
    - name: Remove the cache directory.
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/cache"
        state: absent
    - name: Apply manifests
      ansible.builtin.command: "kubectl --kubeconfig {{ kube_config }} apply -f {{ item }}"
      loop: "{{ hostvars[groups.kube_nodes.0].kube_manifests }}"
      retries: 3
      delay: 10
      register: ctl_res
      until: ctl_res.rc == 0

- name: Join additional control planes
  hosts: kube_master[1:]
  vars:
    join_cmd: "{{ lookup('file', 'files/_kube_join_controlplane') }}"
  tasks:
    - name: Initialize join
      become: true
      ansible.builtin.command: "{{ join_cmd }}"

- name: Join worker nodes
  hosts: kube_worker
  vars:
    join_cmd: "{{ lookup('file', 'files/_kube_join_worker') }}"
  tasks:
    - name: Initialize join
      become: true
      ansible.builtin.command: "{{ join_cmd }}"
