- name: Download and install qbec
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/splunk/qbec/releases/download/v{{ hostvars[groups.kube_nodes.0].qbec_version }}/qbec-linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    exclude:
      - "CHANGELOG.md"
      - "README.md"
      - "LICENSE"
  when:
    - hostvars[groups.kube_nodes.0].qbec_version is defined
    - hostvars[groups.kube_nodes.0].qbec_version != ""
