- name: TEST play
  hosts: gitlab
  tasks:
    - debug:
        var: hostvars[inventory_hostname]
    - name: Restart Gitlab container
      containers.podman.podman_container:
        name: gitlab
        state: started
        force_restart: true
      register: rst_res
      retries: 10
      delay: 6
      until: rst_res.changed
    - debug:
        var: rst_res
    - name: Check GitLab ready
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ gitlab_port }}/"
        follow_redirects: safe
      register: url_res
      retries: 30
      delay: 10
      until: url_res.status == 200
